In [6]:
import numpy as np
import pandas as pd
import json
from urllib.request import urlopen

# 1. Driver Standings

In [7]:
url = 'http://ergast.com/api/f1/current/driverStandings.json'
response = urlopen(url)
raw_data = response.read().decode('utf-8')

data = json.loads(raw_data)
        
df_standings = pd.json_normalize(data['MRData']['StandingsTable']['StandingsLists'][0]['DriverStandings'])
df_standings.head()

,position,positionText,points,wins,Constructors,Driver.driverId,Driver.permanentNumber,Driver.code,Driver.url,Driver.givenName,Driver.familyName,Driver.dateOfBirth,Driver.nationality
0,1,1,295,7,"[{'constructorId': 'red_bull', 'url': 'http://...",max_verstappen,33,VER,http://en.wikipedia.org/wiki/Max_Verstappen,Max,Verstappen,1997-09-30,Dutch
1,2,2,225,2,"[{'constructorId': 'mclaren', 'url': 'http://e...",norris,4,NOR,http://en.wikipedia.org/wiki/Lando_Norris,Lando,Norris,1999-11-13,British
2,3,3,192,1,"[{'constructorId': 'ferrari', 'url': 'http://e...",leclerc,16,LEC,http://en.wikipedia.org/wiki/Charles_Leclerc,Charles,Leclerc,1997-10-16,Monegasque
3,4,4,179,1,"[{'constructorId': 'mclaren', 'url': 'http://e...",piastri,81,PIA,http://en.wikipedia.org/wiki/Oscar_Piastri,Oscar,Piastri,2001-04-06,Australian
4,5,5,172,1,"[{'constructorId': 'ferrari', 'url': 'http://e...",sainz,55,SAI,http://en.wikipedia.org/wiki/Carlos_Sainz_Jr.,Carlos,Sainz,1994-09-01,Spanish

In [8]:
df_standings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   position                21 non-null     object
 1   positionText            21 non-null     object
 2   points                  21 non-null     object
 3   wins                    21 non-null     object
 4   Constructors            21 non-null     object
 5   Driver.driverId         21 non-null     object
 6   Driver.permanentNumber  21 non-null     object
 7   Driver.code             21 non-null     object
 8   Driver.url              21 non-null     object
 9   Driver.givenName        21 non-null     object
 10  Driver.familyName       21 non-null     object
 11  Driver.dateOfBirth      21 non-null     object
 12  Driver.nationality      21 non-null     object
dtypes: object(13)
memory usage: 2.3+ KB

In [9]:
df_standings["Constructors"] = df_standings["Constructors"].apply(lambda x:x[0]["constructorId"])
df_standings["Constructors"]

0         red_bull
1          mclaren
2          ferrari
3          mclaren
4          ferrari
5         mercedes
6         red_bull
7         mercedes
8     aston_martin
9     aston_martin
10            haas
11              rb
12              rb
13          alpine
14         ferrari
15            haas
16          alpine
17        williams
18          sauber
19        williams
20          sauber
Name: Constructors, dtype: object

In [10]:
df_standings["Constructors"] = df_standings["Constructors"].replace("alpine", "BWT Alpine F1 Team")
df_standings["Constructors"] = df_standings["Constructors"].replace("haas", "MoneyGram Haas F1 Team")
df_standings["Constructors"] = df_standings["Constructors"].replace("mercedes", "Mercedes-AMG PETRONAS F1 Team")
df_standings["Constructors"] = df_standings["Constructors"].replace("williams", "Williams Racing")
df_standings["Constructors"] = df_standings["Constructors"].replace("aston_martin", "Aston Martin Aramco F1 Team")
df_standings["Constructors"] = df_standings["Constructors"].replace("sauber", "Stake F1 Team Kick Sauber")
df_standings["Constructors"] = df_standings["Constructors"].replace("rb", "Visa Cash App RB Formula One Team")
df_standings["Constructors"] = df_standings["Constructors"].replace("ferrari", "Scuderia Ferrari")
df_standings["Constructors"] = df_standings["Constructors"].replace("mclaren", "McLaren Formula 1 Team")
df_standings["Constructors"] = df_standings["Constructors"].replace("red_bull", "Oracle Red Bull Racing")
df_standings["Constructors"]

0                Oracle Red Bull Racing
1                McLaren Formula 1 Team
2                      Scuderia Ferrari
3                McLaren Formula 1 Team
4                      Scuderia Ferrari
5         Mercedes-AMG PETRONAS F1 Team
6                Oracle Red Bull Racing
7         Mercedes-AMG PETRONAS F1 Team
8           Aston Martin Aramco F1 Team
9           Aston Martin Aramco F1 Team
10               MoneyGram Haas F1 Team
11    Visa Cash App RB Formula One Team
12    Visa Cash App RB Formula One Team
13                   BWT Alpine F1 Team
14                     Scuderia Ferrari
15               MoneyGram Haas F1 Team
16                   BWT Alpine F1 Team
17                      Williams Racing
18            Stake F1 Team Kick Sauber
19                      Williams Racing
20            Stake F1 Team Kick Sauber
Name: Constructors, dtype: object

In [11]:
df_standings.head()

,position,positionText,points,wins,Constructors,Driver.driverId,Driver.permanentNumber,Driver.code,Driver.url,Driver.givenName,Driver.familyName,Driver.dateOfBirth,Driver.nationality
0,1,1,295,7,Oracle Red Bull Racing,max_verstappen,33,VER,http://en.wikipedia.org/wiki/Max_Verstappen,Max,Verstappen,1997-09-30,Dutch
1,2,2,225,2,McLaren Formula 1 Team,norris,4,NOR,http://en.wikipedia.org/wiki/Lando_Norris,Lando,Norris,1999-11-13,British
2,3,3,192,1,Scuderia Ferrari,leclerc,16,LEC,http://en.wikipedia.org/wiki/Charles_Leclerc,Charles,Leclerc,1997-10-16,Monegasque
3,4,4,179,1,McLaren Formula 1 Team,piastri,81,PIA,http://en.wikipedia.org/wiki/Oscar_Piastri,Oscar,Piastri,2001-04-06,Australian
4,5,5,172,1,Scuderia Ferrari,sainz,55,SAI,http://en.wikipedia.org/wiki/Carlos_Sainz_Jr.,Carlos,Sainz,1994-09-01,Spanish

In [12]:
df_standings["full_name"] = df_standings['Driver.givenName'] + ' ' + df_standings['Driver.familyName']
df_standings["full_name"]

0       Max Verstappen
1         Lando Norris
2      Charles Leclerc
3        Oscar Piastri
4         Carlos Sainz
5       Lewis Hamilton
6         Sergio Pérez
7       George Russell
8      Fernando Alonso
9         Lance Stroll
10     Nico Hülkenberg
11        Yuki Tsunoda
12    Daniel Ricciardo
13        Pierre Gasly
14      Oliver Bearman
15     Kevin Magnussen
16        Esteban Ocon
17     Alexander Albon
18         Guanyu Zhou
19      Logan Sargeant
20     Valtteri Bottas
Name: full_name, dtype: object

In [13]:
df_standings["Driver.permanentNumber"] = df_standings["Driver.permanentNumber"].replace("33", "1")
df_standings.head()

,position,positionText,points,wins,Constructors,Driver.driverId,Driver.permanentNumber,Driver.code,Driver.url,Driver.givenName,Driver.familyName,Driver.dateOfBirth,Driver.nationality,full_name
0,1,1,295,7,Oracle Red Bull Racing,max_verstappen,1,VER,http://en.wikipedia.org/wiki/Max_Verstappen,Max,Verstappen,1997-09-30,Dutch,Max Verstappen
1,2,2,225,2,McLaren Formula 1 Team,norris,4,NOR,http://en.wikipedia.org/wiki/Lando_Norris,Lando,Norris,1999-11-13,British,Lando Norris
2,3,3,192,1,Scuderia Ferrari,leclerc,16,LEC,http://en.wikipedia.org/wiki/Charles_Leclerc,Charles,Leclerc,1997-10-16,Monegasque,Charles Leclerc
3,4,4,179,1,McLaren Formula 1 Team,piastri,81,PIA,http://en.wikipedia.org/wiki/Oscar_Piastri,Oscar,Piastri,2001-04-06,Australian,Oscar Piastri
4,5,5,172,1,Scuderia Ferrari,sainz,55,SAI,http://en.wikipedia.org/wiki/Carlos_Sainz_Jr.,Carlos,Sainz,1994-09-01,Spanish,Carlos Sainz

# 2. Constructors Standings

In [20]:
import xml.etree.ElementTree as ET
import pandas as pd
from urllib.request import urlopen

# Load the data
url = 'http://ergast.com/api/f1/current/constructorStandings'
response = urlopen(url)
raw_data = response.read().decode('utf-8')

root = ET.fromstring(raw_data)

namespace = {'ns': 'http://ergast.com/mrd/1.5'}
standings_list = []

for standing in root.findall('.//ns:ConstructorStanding', namespaces=namespace):
    position = standing.get('position')
    points = standing.get('points')
    wins = standing.get('wins')
    constructor = standing.find('ns:Constructor/ns:Name', namespaces=namespace).text
    nationality = standing.find('ns:Constructor/ns:Nationality', namespaces=namespace).text
    
    standings_list.append({
        'Position': position,
        'Points': points,
        'Wins': wins,
        'Constructor': constructor,
        'Nationality': nationality
    })

# Convert to DataFrame
df_standings_c = pd.DataFrame(standings_list)
df_standings_c

  Position Points Wins     Constructor Nationality
0        1    434    7        Red Bull    Austrian
1        2    404    3         McLaren     British
2        3    370    2         Ferrari     Italian
3        4    276    3        Mercedes      German
4        5     74    0    Aston Martin     British
5        6     34    0      RB F1 Team     Italian
6        7     27    0    Haas F1 Team    American
7        8     13    0  Alpine F1 Team      French
8        9      4    0        Williams     British
9       10      0    0          Sauber       Swiss

# 3. Mclaren Constructor Standings

In [26]:
url = 'https://ergast.com/api/f1/constructors/mclaren/constructorstandings?limit=30&offset=30'
response = urlopen(url)
raw_data = response.read().decode('utf-8')
print(raw_data)

<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="/schemas/mrd-1.5.xsl"?>
<MRData xmlns="http://ergast.com/mrd/1.5" series="f1" url="http://ergast.com/api/f1/constructors/mclaren/constructorstandings" limit="30" offset="30" total="54">
	<StandingsTable constructorId="mclaren">
		<StandingsList season="2000" round="17">
			<ConstructorStanding position="2" positionText="2" points="162" wins="7">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2001" round="17">
			<ConstructorStanding position="2" positionText="2" points="102" wins="4">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2002" round="17">
			<ConstructorStanding position="3" positionText="3" points="65" wins="1">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2003" round="16">
			<ConstructorStanding position="3" positionText="3" points="142" wins="2">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2004" round="18">
			<ConstructorStanding position="5" positionText="5" points="69" wins="1">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2005" round="19">
			<ConstructorStanding position="2" positionText="2" points="182" wins="10">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2006" round="18">
			<ConstructorStanding position="3" positionText="3" points="110" wins="0">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2007" round="17">
			<ConstructorStanding position="11" positionText="E" points="218" wins="8">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2008" round="18">
			<ConstructorStanding position="2" positionText="2" points="151" wins="6">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2009" round="17">
			<ConstructorStanding position="3" positionText="3" points="71" wins="2">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2010" round="19">
			<ConstructorStanding position="2" positionText="2" points="454" wins="5">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2011" round="19">
			<ConstructorStanding position="2" positionText="2" points="497" wins="6">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2012" round="20">
			<ConstructorStanding position="3" positionText="3" points="378" wins="7">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2013" round="19">
			<ConstructorStanding position="5" positionText="5" points="122" wins="0">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2014" round="19">
			<ConstructorStanding position="5" positionText="5" points="181" wins="0">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2015" round="19">
			<ConstructorStanding position="9" positionText="9" points="27" wins="0">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2016" round="21">
			<ConstructorStanding position="6" positionText="6" points="76" wins="0">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2017" round="20">
			<ConstructorStanding position="9" positionText="9" points="30" wins="0">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2018" round="21">
			<ConstructorStanding position="6" positionText="6" points="62" wins="0">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2019" round="21">
			<ConstructorStanding position="4" positionText="4" points="145" wins="0">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2020" round="17">
			<ConstructorStanding position="3" positionText="3" points="202" wins="0">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2021" round="22">
			<ConstructorStanding position="4" positionText="4" points="275" wins="1">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2022" round="22">
			<ConstructorStanding position="5" positionText="5" points="159" wins="0">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2023" round="22">
			<ConstructorStanding position="4" positionText="4" points="302" wins="0">
				<Constructor constructorId="mclaren" url="http://en.wikipedia.org/wiki/McLaren">
					<Name>McLaren</Name>
					<Nationality>British</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
	</StandingsTable></MRData>

In [27]:
root = ET.fromstring(raw_data)

namespace = {'ns': 'http://ergast.com/mrd/1.5'}
standings_list = []

for standing in root.findall('.//ns:ConstructorStanding', namespaces=namespace):
    position = standing.get('position')
    points = standing.get('points')
    wins = standing.get('wins')

    constructor_element = standing.find('ns:Constructor', namespaces=namespace)
    if constructor_element is not None:
        constructor = constructor_element.find('ns:Name', namespaces=namespace).text
        nationality = constructor_element.find('ns:Nationality', namespaces=namespace).text
    
    standings_list.append({
        'Position': position,
        'Points': points,
        'Wins': wins,
        'Constructor': constructor,
        'Nationality': nationality
        })

# Convert to DataFrame
mclaren_standings = pd.DataFrame(standings_list)
mclaren_standings

   Position Points Wins Constructor Nationality
0         2    162    7     McLaren     British
1         2    102    4     McLaren     British
2         3     65    1     McLaren     British
3         3    142    2     McLaren     British
4         5     69    1     McLaren     British
5         2    182   10     McLaren     British
6         3    110    0     McLaren     British
7        11    218    8     McLaren     British
8         2    151    6     McLaren     British
9         3     71    2     McLaren     British
10        2    454    5     McLaren     British
11        2    497    6     McLaren     British
12        3    378    7     McLaren     British
13        5    122    0     McLaren     British
14        5    181    0     McLaren     British
15        9     27    0     McLaren     British
16        6     76    0     McLaren     British
17        9     30    0     McLaren     British
18        6     62    0     McLaren     British
19        4    145    0     McLaren     British
20        3    202    0     McLaren     British
21        4    275    1     McLaren     British
22        5    159    0     McLaren     British
23        4    302    0     McLaren     British

In [37]:
mclaren_standings.loc[24] = ['2', '404', '3', 'McLaren', 'British']
mclaren_standings

   Position Points Wins Constructor Nationality
0         2    162    7     McLaren     British
1         2    102    4     McLaren     British
2         3     65    1     McLaren     British
3         3    142    2     McLaren     British
4         5     69    1     McLaren     British
5         2    182   10     McLaren     British
6         3    110    0     McLaren     British
7        11    218    8     McLaren     British
8         2    151    6     McLaren     British
9         3     71    2     McLaren     British
10        2    454    5     McLaren     British
11        2    497    6     McLaren     British
12        3    378    7     McLaren     British
13        5    122    0     McLaren     British
14        5    181    0     McLaren     British
15        9     27    0     McLaren     British
16        6     76    0     McLaren     British
17        9     30    0     McLaren     British
18        6     62    0     McLaren     British
19        4    145    0     McLaren     British
20        3    202    0     McLaren     British
21        4    275    1     McLaren     British
22        5    159    0     McLaren     British
23        4    302    0     McLaren     British
24        2    404    3     McLaren     British

In [41]:
mclaren_standings["Year"] = np.arange(2000, 2025)
mclaren_standings

   Position Points Wins Constructor Nationality  Year
0         2    162    7     McLaren     British  2000
1         2    102    4     McLaren     British  2001
2         3     65    1     McLaren     British  2002
3         3    142    2     McLaren     British  2003
4         5     69    1     McLaren     British  2004
5         2    182   10     McLaren     British  2005
6         3    110    0     McLaren     British  2006
7        11    218    8     McLaren     British  2007
8         2    151    6     McLaren     British  2008
9         3     71    2     McLaren     British  2009
10        2    454    5     McLaren     British  2010
11        2    497    6     McLaren     British  2011
12        3    378    7     McLaren     British  2012
13        5    122    0     McLaren     British  2013
14        5    181    0     McLaren     British  2014
15        9     27    0     McLaren     British  2015
16        6     76    0     McLaren     British  2016
17        9     30    0     McLaren     British  2017
18        6     62    0     McLaren     British  2018
19        4    145    0     McLaren     British  2019
20        3    202    0     McLaren     British  2020
21        4    275    1     McLaren     British  2021
22        5    159    0     McLaren     British  2022
23        4    302    0     McLaren     British  2023
24        2    404    3     McLaren     British  2024

In [44]:
mclaren_standings.rename(columns={col: f"{col}_mc" for col in mclaren_standings.columns if col != "Year"}, inplace=True)
mclaren_standings

   Position_mc Points_mc Wins_mc Constructor_mc Nationality_mc  Year
0            2       162       7        McLaren        British  2000
1            2       102       4        McLaren        British  2001
2            3        65       1        McLaren        British  2002
3            3       142       2        McLaren        British  2003
4            5        69       1        McLaren        British  2004
5            2       182      10        McLaren        British  2005
6            3       110       0        McLaren        British  2006
7           11       218       8        McLaren        British  2007
8            2       151       6        McLaren        British  2008
9            3        71       2        McLaren        British  2009
10           2       454       5        McLaren        British  2010
11           2       497       6        McLaren        British  2011
12           3       378       7        McLaren        British  2012
13           5       122       0        McLaren        British  2013
14           5       181       0        McLaren        British  2014
15           9        27       0        McLaren        British  2015
16           6        76       0        McLaren        British  2016
17           9        30       0        McLaren        British  2017
18           6        62       0        McLaren        British  2018
19           4       145       0        McLaren        British  2019
20           3       202       0        McLaren        British  2020
21           4       275       1        McLaren        British  2021
22           5       159       0        McLaren        British  2022
23           4       302       0        McLaren        British  2023
24           2       404       3        McLaren        British  2024

# 4. Mercedes Standings

In [29]:
url = 'https://ergast.com/api/f1/constructors/mercedes/constructorstandings'
response = urlopen(url)
raw_data = response.read().decode('utf-8')
print(raw_data)

<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="/schemas/mrd-1.5.xsl"?>
<MRData xmlns="http://ergast.com/mrd/1.5" series="f1" url="http://ergast.com/api/f1/constructors/mercedes/constructorstandings" limit="30" offset="0" total="14">
	<StandingsTable constructorId="mercedes">
		<StandingsList season="2010" round="19">
			<ConstructorStanding position="4" positionText="4" points="214" wins="0">
				<Constructor constructorId="mercedes" url="http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One">
					<Name>Mercedes</Name>
					<Nationality>German</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2011" round="19">
			<ConstructorStanding position="4" positionText="4" points="165" wins="0">
				<Constructor constructorId="mercedes" url="http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One">
					<Name>Mercedes</Name>
					<Nationality>German</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2012" round="20">
			<ConstructorStanding position="5" positionText="5" points="142" wins="1">
				<Constructor constructorId="mercedes" url="http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One">
					<Name>Mercedes</Name>
					<Nationality>German</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2013" round="19">
			<ConstructorStanding position="2" positionText="2" points="360" wins="3">
				<Constructor constructorId="mercedes" url="http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One">
					<Name>Mercedes</Name>
					<Nationality>German</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2014" round="19">
			<ConstructorStanding position="1" positionText="1" points="701" wins="16">
				<Constructor constructorId="mercedes" url="http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One">
					<Name>Mercedes</Name>
					<Nationality>German</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2015" round="19">
			<ConstructorStanding position="1" positionText="1" points="703" wins="16">
				<Constructor constructorId="mercedes" url="http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One">
					<Name>Mercedes</Name>
					<Nationality>German</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2016" round="21">
			<ConstructorStanding position="1" positionText="1" points="765" wins="19">
				<Constructor constructorId="mercedes" url="http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One">
					<Name>Mercedes</Name>
					<Nationality>German</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2017" round="20">
			<ConstructorStanding position="1" positionText="1" points="668" wins="12">
				<Constructor constructorId="mercedes" url="http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One">
					<Name>Mercedes</Name>
					<Nationality>German</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2018" round="21">
			<ConstructorStanding position="1" positionText="1" points="655" wins="11">
				<Constructor constructorId="mercedes" url="http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One">
					<Name>Mercedes</Name>
					<Nationality>German</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2019" round="21">
			<ConstructorStanding position="1" positionText="1" points="739" wins="15">
				<Constructor constructorId="mercedes" url="http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One">
					<Name>Mercedes</Name>
					<Nationality>German</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2020" round="17">
			<ConstructorStanding position="1" positionText="1" points="573" wins="13">
				<Constructor constructorId="mercedes" url="http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One">
					<Name>Mercedes</Name>
					<Nationality>German</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2021" round="22">
			<ConstructorStanding position="1" positionText="1" points="613.5" wins="9">
				<Constructor constructorId="mercedes" url="http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One">
					<Name>Mercedes</Name>
					<Nationality>German</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2022" round="22">
			<ConstructorStanding position="3" positionText="3" points="515" wins="1">
				<Constructor constructorId="mercedes" url="http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One">
					<Name>Mercedes</Name>
					<Nationality>German</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2023" round="22">
			<ConstructorStanding position="2" positionText="2" points="409" wins="0">
				<Constructor constructorId="mercedes" url="http://en.wikipedia.org/wiki/Mercedes-Benz_in_Formula_One">
					<Name>Mercedes</Name>
					<Nationality>German</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
	</StandingsTable></MRData>

In [30]:
root = ET.fromstring(raw_data)

namespace = {'ns': 'http://ergast.com/mrd/1.5'}
standings_list = []

for standing in root.findall('.//ns:ConstructorStanding', namespaces=namespace):
    position = standing.get('position')
    points = standing.get('points')
    wins = standing.get('wins')

    constructor_element = standing.find('ns:Constructor', namespaces=namespace)
    if constructor_element is not None:
        constructor = constructor_element.find('ns:Name', namespaces=namespace).text
        nationality = constructor_element.find('ns:Nationality', namespaces=namespace).text
    
    standings_list.append({
        'Position': position,
        'Points': points,
        'Wins': wins,
        'Constructor': constructor,
        'Nationality': nationality
        })

# Convert to DataFrame
mercedes_standings = pd.DataFrame(standings_list)
mercedes_standings

   Position Points Wins Constructor Nationality
0         4    214    0    Mercedes      German
1         4    165    0    Mercedes      German
2         5    142    1    Mercedes      German
3         2    360    3    Mercedes      German
4         1    701   16    Mercedes      German
5         1    703   16    Mercedes      German
6         1    765   19    Mercedes      German
7         1    668   12    Mercedes      German
8         1    655   11    Mercedes      German
9         1    739   15    Mercedes      German
10        1    573   13    Mercedes      German
11        1  613.5    9    Mercedes      German
12        3    515    1    Mercedes      German
13        2    409    0    Mercedes      German

In [38]:
mercedes_standings.loc[14] = ['4', '276', '3', 'Mercedes', 'German']
mercedes_standings

   Position Points Wins Constructor Nationality
0         4    214    0    Mercedes      German
1         4    165    0    Mercedes      German
2         5    142    1    Mercedes      German
3         2    360    3    Mercedes      German
4         1    701   16    Mercedes      German
5         1    703   16    Mercedes      German
6         1    765   19    Mercedes      German
7         1    668   12    Mercedes      German
8         1    655   11    Mercedes      German
9         1    739   15    Mercedes      German
10        1    573   13    Mercedes      German
11        1  613.5    9    Mercedes      German
12        3    515    1    Mercedes      German
13        2    409    0    Mercedes      German
14        4    276    3    Mercedes      German

In [42]:
mercedes_standings["Year"] = np.arange(2010, 2025)
mercedes_standings

   Position Points Wins Constructor Nationality  Year
0         4    214    0    Mercedes      German  2010
1         4    165    0    Mercedes      German  2011
2         5    142    1    Mercedes      German  2012
3         2    360    3    Mercedes      German  2013
4         1    701   16    Mercedes      German  2014
5         1    703   16    Mercedes      German  2015
6         1    765   19    Mercedes      German  2016
7         1    668   12    Mercedes      German  2017
8         1    655   11    Mercedes      German  2018
9         1    739   15    Mercedes      German  2019
10        1    573   13    Mercedes      German  2020
11        1  613.5    9    Mercedes      German  2021
12        3    515    1    Mercedes      German  2022
13        2    409    0    Mercedes      German  2023
14        4    276    3    Mercedes      German  2024

In [45]:
mercedes_standings.rename(columns={col: f"{col}_md" for col in mercedes_standings.columns if col != "Year"}, inplace=True)
mercedes_standings

   Position_md Points_md Wins_md Constructor_md Nationality_md  Year
0            4       214       0       Mercedes         German  2010
1            4       165       0       Mercedes         German  2011
2            5       142       1       Mercedes         German  2012
3            2       360       3       Mercedes         German  2013
4            1       701      16       Mercedes         German  2014
5            1       703      16       Mercedes         German  2015
6            1       765      19       Mercedes         German  2016
7            1       668      12       Mercedes         German  2017
8            1       655      11       Mercedes         German  2018
9            1       739      15       Mercedes         German  2019
10           1       573      13       Mercedes         German  2020
11           1     613.5       9       Mercedes         German  2021
12           3       515       1       Mercedes         German  2022
13           2       409       0       Mercedes         German  2023
14           4       276       3       Mercedes         German  2024

# 5. Redbull Standings

In [32]:
url = 'https://ergast.com/api/f1/constructors/red_bull/constructorstandings'
response = urlopen(url)
raw_data = response.read().decode('utf-8')
print(raw_data)

<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="/schemas/mrd-1.5.xsl"?>
<MRData xmlns="http://ergast.com/mrd/1.5" series="f1" url="http://ergast.com/api/f1/constructors/red_bull/constructorstandings" limit="30" offset="0" total="19">
	<StandingsTable constructorId="red_bull">
		<StandingsList season="2005" round="19">
			<ConstructorStanding position="7" positionText="7" points="34" wins="0">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2006" round="18">
			<ConstructorStanding position="7" positionText="7" points="16" wins="0">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2007" round="17">
			<ConstructorStanding position="5" positionText="5" points="24" wins="0">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2008" round="18">
			<ConstructorStanding position="7" positionText="7" points="29" wins="0">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2009" round="17">
			<ConstructorStanding position="2" positionText="2" points="153.5" wins="6">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2010" round="19">
			<ConstructorStanding position="1" positionText="1" points="498" wins="9">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2011" round="19">
			<ConstructorStanding position="1" positionText="1" points="650" wins="12">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2012" round="20">
			<ConstructorStanding position="1" positionText="1" points="460" wins="7">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2013" round="19">
			<ConstructorStanding position="1" positionText="1" points="596" wins="13">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2014" round="19">
			<ConstructorStanding position="2" positionText="2" points="405" wins="3">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2015" round="19">
			<ConstructorStanding position="4" positionText="4" points="187" wins="0">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2016" round="21">
			<ConstructorStanding position="2" positionText="2" points="468" wins="2">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2017" round="20">
			<ConstructorStanding position="3" positionText="3" points="368" wins="3">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2018" round="21">
			<ConstructorStanding position="3" positionText="3" points="419" wins="4">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2019" round="21">
			<ConstructorStanding position="3" positionText="3" points="417" wins="3">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2020" round="17">
			<ConstructorStanding position="2" positionText="2" points="319" wins="2">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2021" round="22">
			<ConstructorStanding position="2" positionText="2" points="585.5" wins="11">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2022" round="22">
			<ConstructorStanding position="1" positionText="1" points="759" wins="17">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
		<StandingsList season="2023" round="22">
			<ConstructorStanding position="1" positionText="1" points="860" wins="21">
				<Constructor constructorId="red_bull" url="http://en.wikipedia.org/wiki/Red_Bull_Racing">
					<Name>Red Bull</Name>
					<Nationality>Austrian</Nationality>
				</Constructor>
			</ConstructorStanding>
		</StandingsList>
	</StandingsTable></MRData>

In [33]:
root = ET.fromstring(raw_data)

namespace = {'ns': 'http://ergast.com/mrd/1.5'}
standings_list = []

for standing in root.findall('.//ns:ConstructorStanding', namespaces=namespace):
    position = standing.get('position')
    points = standing.get('points')
    wins = standing.get('wins')

    constructor_element = standing.find('ns:Constructor', namespaces=namespace)
    if constructor_element is not None:
        constructor = constructor_element.find('ns:Name', namespaces=namespace).text
        nationality = constructor_element.find('ns:Nationality', namespaces=namespace).text
    
    standings_list.append({
        'Position': position,
        'Points': points,
        'Wins': wins,
        'Constructor': constructor,
        'Nationality': nationality
        })

# Convert to DataFrame
redbull_standings = pd.DataFrame(standings_list)
redbull_standings

   Position Points Wins Constructor Nationality
0         7     34    0    Red Bull    Austrian
1         7     16    0    Red Bull    Austrian
2         5     24    0    Red Bull    Austrian
3         7     29    0    Red Bull    Austrian
4         2  153.5    6    Red Bull    Austrian
5         1    498    9    Red Bull    Austrian
6         1    650   12    Red Bull    Austrian
7         1    460    7    Red Bull    Austrian
8         1    596   13    Red Bull    Austrian
9         2    405    3    Red Bull    Austrian
10        4    187    0    Red Bull    Austrian
11        2    468    2    Red Bull    Austrian
12        3    368    3    Red Bull    Austrian
13        3    419    4    Red Bull    Austrian
14        3    417    3    Red Bull    Austrian
15        2    319    2    Red Bull    Austrian
16        2  585.5   11    Red Bull    Austrian
17        1    759   17    Red Bull    Austrian
18        1    860   21    Red Bull    Austrian

In [40]:
redbull_standings.loc[19] = ['1', '434', '7', 'Red Bull', 'Austrian']
redbull_standings

   Position Points Wins Constructor Nationality
0         7     34    0    Red Bull    Austrian
1         7     16    0    Red Bull    Austrian
2         5     24    0    Red Bull    Austrian
3         7     29    0    Red Bull    Austrian
4         2  153.5    6    Red Bull    Austrian
5         1    498    9    Red Bull    Austrian
6         1    650   12    Red Bull    Austrian
7         1    460    7    Red Bull    Austrian
8         1    596   13    Red Bull    Austrian
9         2    405    3    Red Bull    Austrian
10        4    187    0    Red Bull    Austrian
11        2    468    2    Red Bull    Austrian
12        3    368    3    Red Bull    Austrian
13        3    419    4    Red Bull    Austrian
14        3    417    3    Red Bull    Austrian
15        2    319    2    Red Bull    Austrian
16        2  585.5   11    Red Bull    Austrian
17        1    759   17    Red Bull    Austrian
18        1    860   21    Red Bull    Austrian
19        1    434    7    Red Bull    Austrian

In [43]:
redbull_standings["Year"] = np.arange(2005, 2025)
redbull_standings

   Position Points Wins Constructor Nationality  Year
0         7     34    0    Red Bull    Austrian  2005
1         7     16    0    Red Bull    Austrian  2006
2         5     24    0    Red Bull    Austrian  2007
3         7     29    0    Red Bull    Austrian  2008
4         2  153.5    6    Red Bull    Austrian  2009
5         1    498    9    Red Bull    Austrian  2010
6         1    650   12    Red Bull    Austrian  2011
7         1    460    7    Red Bull    Austrian  2012
8         1    596   13    Red Bull    Austrian  2013
9         2    405    3    Red Bull    Austrian  2014
10        4    187    0    Red Bull    Austrian  2015
11        2    468    2    Red Bull    Austrian  2016
12        3    368    3    Red Bull    Austrian  2017
13        3    419    4    Red Bull    Austrian  2018
14        3    417    3    Red Bull    Austrian  2019
15        2    319    2    Red Bull    Austrian  2020
16        2  585.5   11    Red Bull    Austrian  2021
17        1    759   17    Red Bull    Austrian  2022
18        1    860   21    Red Bull    Austrian  2023
19        1    434    7    Red Bull    Austrian  2024

In [46]:
redbull_standings.rename(columns={col: f"{col}_rb" for col in redbull_standings.columns if col != 'Year'}, inplace=True)
redbull_standings

   Position_rb Points_rb Wins_rb Constructor_rb Nationality_rb  Year
0            7        34       0       Red Bull       Austrian  2005
1            7        16       0       Red Bull       Austrian  2006
2            5        24       0       Red Bull       Austrian  2007
3            7        29       0       Red Bull       Austrian  2008
4            2     153.5       6       Red Bull       Austrian  2009
5            1       498       9       Red Bull       Austrian  2010
6            1       650      12       Red Bull       Austrian  2011
7            1       460       7       Red Bull       Austrian  2012
8            1       596      13       Red Bull       Austrian  2013
9            2       405       3       Red Bull       Austrian  2014
10           4       187       0       Red Bull       Austrian  2015
11           2       468       2       Red Bull       Austrian  2016
12           3       368       3       Red Bull       Austrian  2017
13           3       419       4       Red Bull       Austrian  2018
14           3       417       3       Red Bull       Austrian  2019
15           2       319       2       Red Bull       Austrian  2020
16           2     585.5      11       Red Bull       Austrian  2021
17           1       759      17       Red Bull       Austrian  2022
18           1       860      21       Red Bull       Austrian  2023
19           1       434       7       Red Bull       Austrian  2024

In [48]:
df_merge = pd.merge(mclaren_standings, mercedes_standings, on="Year", how="outer")
df_merge = pd.merge(df_merge, redbull_standings, on = "Year", how="outer")
df_merge = df_merge[df_merge['Year'] >= 2010]
df_merge

,Position_mc,Points_mc,Wins_mc,Constructor_mc,Nationality_mc,Year,Position_md,Points_md,Wins_md,Constructor_md,Nationality_md,Position_rb,Points_rb,Wins_rb,Constructor_rb,Nationality_rb
10,2,454,5,McLaren,British,2010,4,214,0,Mercedes,German,1,498,9,Red Bull,Austrian
11,2,497,6,McLaren,British,2011,4,165,0,Mercedes,German,1,650,12,Red Bull,Austrian
12,3,378,7,McLaren,British,2012,5,142,1,Mercedes,German,1,460,7,Red Bull,Austrian
13,5,122,0,McLaren,British,2013,2,360,3,Mercedes,German,1,596,13,Red Bull,Austrian
14,5,181,0,McLaren,British,2014,1,701,16,Mercedes,German,2,405,3,Red Bull,Austrian
15,9,27,0,McLaren,British,2015,1,703,16,Mercedes,German,4,187,0,Red Bull,Austrian
16,6,76,0,McLaren,British,2016,1,765,19,Mercedes,German,2,468,2,Red Bull,Austrian
17,9,30,0,McLaren,British,2017,1,668,12,Mercedes,German,3,368,3,Red Bull,Austrian
18,6,62,0,McLaren,British,2018,1,655,11,Mercedes,German,3,419,4,Red Bull,Austrian
19,4,145,0,McLaren,British,2019,1,739,15,Mercedes,German,3,417,3,Red Bull,Austrian
20,3,202,0,McLaren,British,2020,1,573,13,Mercedes,German,2,319,2,Red Bull,Austrian
21,4,275,1,McLaren,British,2021,1,613.5,9,Mercedes,German,2,585.5,11,Red Bull,Austrian
22,5,159,0,McLaren,British,2022,3,515,1,Mercedes,German,1,759,17,Red Bull,Austrian
23,4,302,0,McLaren,British,2023,2,409,0,Mercedes,German,1,860,21,Red Bull,Austrian
24,2,404,3,McLaren,British,2024,4,276,3,Mercedes,German,1,434,7,Red Bull,Austrian

In [64]:
df_merge.to_csv("f1_standings_v1.csv", index=False)